# -*- coding: utf-8 -*-
"""
deploy.py - One-click deployment to Render.
Usage:
    python deploy.py              # interactive mode
    python deploy.py --auto       # fully automated
"""

import argparse
import json
import logging
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s", datefmt="%H:%M:%S")
logger = logging.getLogger("deploy")

BASE_DIR = Path(__file__).resolve().parent
ROOT_DIR = BASE_DIR.parent

ENV_DEFAULTS: dict[str, str] = {
    # RENDER_API_KEY is set via environment variable or will be prompted
    "LINE_CHANNEL_SECRET": os.environ.get("LINE_CHANNEL_SECRET", "4695ff0de6d99851c00fe06234f38c1d"),
    "LINE_CHANNEL_ACCESS_TOKEN": os.environ.get("LINE_CHANNEL_ACCESS_TOKEN", "cCchQly0oKnd/kSJRDo+F473GupP7Ezd0aTQT7Ry8cfjUZTnceXQ98Ij9p2pkFQFh8n3mnimoD6GT8/0SklLJaz5wDovbOtONjRrxzJbkcq4MsMUAX0opLqabjngJ4pblrkaH+DR+QFPS7CO2efUCQdB04t89/1O/w1cDnyilFU="),
    "TARGET_GROUP_ID": os.environ.get("TARGET_GROUP_ID", ""),
    "GMAIL_USER": "itsamliu2025@gmail.com",
    "GMAIL_APP_PASSWORD": os.environ.get("GMAIL_APP_PASSWORD", "uulfdwvlldolvlhw"),
    "REPORT_TO_EMAIL": "itsamliu2025@gmail.com",
    "TZ": "Asia/Taipei",
    "PORT": "5000",
}


def run_cmd(cmd: list[str], cwd: Optional[Path] = None) -> subprocess.CompletedProcess:
    logger.debug("Running: %s", " ".join(cmd))
    return subprocess.run(cmd, cwd=str(cwd or BASE_DIR), capture_output=True, text=True)


def check_prerequisites() -> list[str]:
    missing: list[str] = []
    try:
        result = run_cmd([sys.executable, "--version"])
        if result.returncode != 0:
            missing.append("Python 3.9+")
        else:
            logger.info("Python: %s", result.stdout.strip())
    except FileNotFoundError:
        missing.append("Python 3.9+")
    try:
        result = run_cmd(["git", "--version"])
        if result.returncode != 0:
            missing.append("Git")
        else:
            logger.info("Git: %s", result.stdout.strip())
    except FileNotFoundError:
        missing.append("Git")
    if not os.environ.get("RENDER_API_KEY"):
        logger.warning("RENDER_API_KEY not set - deploy will prompt later")
    else:
        logger.info("RENDER_API_KEY: found")
    return missing


def setup_local_env() -> bool:
    venv_dir = BASE_DIR / "venv"
    if not (venv_dir / "Scripts" / "python.exe").exists():
        logger.info("Creating virtual environment...")
        result = run_cmd([sys.executable, "-m", "venv", str(venv_dir)])
        if result.returncode != 0:
            logger.error("Failed to create venv: %s", result.stderr)
            return False
        logger.info("Virtual environment created.")
    venv_python = venv_dir / "Scripts" / "python.exe"
    logger.info("Upgrading pip...")
    run_cmd([str(venv_python), "-m", "pip", "install", "--upgrade", "pip", "-q"])
    logger.info("Installing dependencies...")
    result = run_cmd([str(venv_python), "-m", "pip", "install", "-r", str(BASE_DIR / "requirements.txt"), "-q"])
    if result.returncode != 0:
        logger.error("pip install failed: %s", result.stderr)
        return False
    logger.info("Dependencies installed.")
    env_path = BASE_DIR / ".env"
    if not env_path.exists():
        logger.info("Creating .env from embedded credentials...")
        lines = [f"# Auto-generated by deploy.py\n"]
        for key, val in ENV_DEFAULTS.items():
            lines.append(f"{key}={val}\n")
        env_path.write_text("".join(lines), encoding="utf-8")
        logger.info(".env created at %s", env_path)
    else:
        logger.info(".env already exists, skipping.")
    return True


def run_tests() -> bool:
    logger.info("Running automated tests...")
    venv_python = BASE_DIR / "venv" / "Scripts" / "python.exe"
    result = run_cmd([str(venv_python), str(BASE_DIR / "test_all.py")], cwd=BASE_DIR)
    if result.returncode != 0:
        logger.error("Tests FAILED:\n%s", result.stdout + result.stderr)
        return False
    logger.info("All tests passed.")
    return True


def git_push() -> bool:
    result = run_cmd(["git", "rev-parse", "--git-dir"], cwd=ROOT_DIR)
    if result.returncode != 0:
        logger.info("Initializing git repository...")
        run_cmd(["git", "init"], cwd=ROOT_DIR)
        root_gitignore = ROOT_DIR / ".gitignore"
        if not root_gitignore.exists():
            root_gitignore.write_text("run/.env\nrun/venv/\nrun/archive/\nrun/logs/\n", encoding="utf-8")
    run_cmd(["git", "add", "-A"], cwd=ROOT_DIR)
    result = run_cmd(["git", "status", "--porcelain"], cwd=ROOT_DIR)
    if result.stdout.strip():
        logger.info("Committing changes...")
        run_cmd(["git", "commit", "-m", "Auto-deploy: LINE Archive Bot"], cwd=ROOT_DIR)
    else:
        logger.info("No changes to commit.")
    repo_url = os.environ.get("GIT_REPO_URL", "")
    if not repo_url:
        logger.warning("GIT_REPO_URL not set - skipping git push.")
        logger.warning("Set GIT_REPO_URL and run again to enable auto-push.")
        return False
    result = run_cmd(["git", "remote", "get-url", "origin"], cwd=ROOT_DIR)
    if result.returncode != 0:
        logger.info("Adding remote origin...")
        run_cmd(["git", "remote", "add", "origin", repo_url], cwd=ROOT_DIR)
    logger.info("Pushing to GitHub...")
    result = run_cmd(["git", "push", "-u", "origin", "main"], cwd=ROOT_DIR)
    if result.returncode != 0:
        result = run_cmd(["git", "push", "-u", "origin", "master"], cwd=ROOT_DIR)
    if result.returncode != 0:
        logger.error("Git push failed: %s", result.stderr)
        logger.warning("Please push manually: git push -u origin main")
        return False
    logger.info("Successfully pushed to GitHub.")
    return True


def trigger_render_deploy() -> bool:
    api_key = os.environ.get("RENDER_API_KEY")
    service_id = os.environ.get("RENDER_SERVICE_ID")
    if not api_key or not service_id:
        logger.warning("RENDER_API_KEY and/or RENDER_SERVICE_ID not set.")
        logger.warning("Skipping Render deploy. Deploy manually from Render dashboard.")
        return False
    import requests
    logger.info("Triggering Render deployment...")
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    url = f"https://api.render.com/v1/services/{service_id}/deploys"
    try:
        resp = requests.post(url, headers=headers, json={}, timeout=30)
        if resp.status_code in (200, 201):
            data = resp.json()
            deploy_id = data.get("id", "unknown")
            logger.info("Render deployment triggered! Deploy ID: %s", deploy_id)
            logger.info("Dashboard: https://dashboard.render.com/web/%s", service_id)
            return True
        else:
            logger.error("Render API error: %s %s", resp.status_code, resp.text)
            return False
    except requests.exceptions.RequestException as e:
        logger.error("Render API request failed: %s", e)
        return False


def generate_report(prerequisites_ok: bool, env_ok: bool, tests_ok: bool, git_ok: bool, deploy_ok: bool) -> str:
    def _row(label: str, ok: bool) -> str:
        icon = "&#10004;" if ok else "&#10008;"
        color = "green" if ok else "red"
        return f"<tr><td>{label}</td><td style=\"color:{color};font-weight:bold;\">{icon} {'PASS' if ok else 'FAIL'}</td></tr>"
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    overall_ok = all([prerequisites_ok, env_ok, tests_ok, git_ok, deploy_ok])
    html = f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Deployment Report - LINE Archive Bot</title>
<style>
body {{ font-family: 'Segoe UI', Arial, sans-serif; max-width: 720px; margin: 40px auto; padding: 0 20px; }}
h1 {{ color: #333; border-bottom: 2px solid #eee; padding-bottom: 8px; }}
table {{ width: 100%; border-collapse: collapse; margin: 16px 0; }}
th, td {{ text-align: left; padding: 10px 12px; border-bottom: 1px solid #eee; }}
th {{ background: #f8f8f8; }}
.pass {{ background: #e8f5e9; }}
.fail {{ background: #ffebee; }}
</style>
</head>
<body>
<h1>Deployment Report - LINE Archive Bot</h1>
<p>Generated: {timestamp}</p>
<table><tr><th>Step</th><th>Status</th></tr>
{_row("Prerequisites Check", prerequisites_ok)}
{_row("Local Environment Setup", env_ok)}
{_row("Automated Tests", tests_ok)}
{_row("Git Push", git_ok)}
{_row("Render Deploy", deploy_ok)}
</table>
<div class="{'pass' if overall_ok else 'fail'}" style="padding:12px;border-radius:6px;font-weight:bold;">
Overall: {'ALL STEPS PASSED' if overall_ok else 'SOME STEPS FAILED'}
</div>
</body></html>"""
    report_path = BASE_DIR / "deploy_report.html"
    report_path.write_text(html, encoding="utf-8")
    logger.info("Deployment report saved to %s", report_path)
    return str(report_path)


def main() -> int:
    parser = argparse.ArgumentParser(description="One-click deployment: LINE Archive Bot -> Render")
    parser.add_argument("--auto", action="store_true", help="Fully automated mode")
    args = parser.parse_args()
    logger.info("LINE Archive Bot - Deployment Script")
    logger.info("[Step 1/5] Checking prerequisites...")
    missing = check_prerequisites()
    prerequisites_ok = len(missing) == 0
    if missing:
        logger.warning("Missing: %s", ", ".join(missing))
        if not args.auto:
            if input("Continue anyway? (y/N): ").strip().lower() != "y":
                logger.info("Deployment aborted.")
                return 1
    logger.info("[Step 2/5] Setting up local environment...")
    env_ok = setup_local_env()
    logger.info("[Step 3/5] Running automated tests...")
    tests_ok = run_tests()
    logger.info("[Step 4/5] Pushing to GitHub...")
    git_ok = git_push()
    logger.info("[Step 5/5] Triggering Render deployment...")
    deploy_ok = trigger_render_deploy()
    report_path = generate_report(prerequisites_ok, env_ok, tests_ok, git_ok, deploy_ok)
    logger.info("Deployment complete! Report: %s", report_path)
    return 0 if all([prerequisites_ok, env_ok, tests_ok]) else 1


if __name__ == "__main__":
    sys.exit(main())


