name: Daily Email Report
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"
jobs:
  send-report:
    runs-on: ubuntu-latest
    steps:
      - name: Test python
        run: |
          python3 -c "
          print('hello')
          "
